version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: serp-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  python-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: serp-api
    ports:
      - "8000:8000"
    env_file:
      - ../.env.production
    environment:
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGINS=https://serpradio.com
      - NODE_ENV=production
      - ALLOWED_ORIGINS=https://serpradio.com
      - USE_SAMPLE_DATA=true
    volumes:
      - ../src:/app/src
      - ../config:/app/config
      - ../data:/app/data
      - ../widget:/app/widget
    depends_on:
      redis:
        condition: service_healthy
    command: python -m src.live_server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  publisher:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: serp-publisher
    env_file:
      - ../.env.production
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    volumes:
      - ../src:/app/src
      - ../config:/app/config
      - ../data:/app/data
    depends_on:
      redis:
        condition: service_healthy
    command: python -m src.publisher --live
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; r=redis.Redis(host='redis'); r.ping()"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  vite-client:
    build:
      context: ../ui
      dockerfile: Dockerfile.dev
    container_name: serp-ui
    ports:
      - "5173:5173"
    environment:
      - VITE_WS_URL=ws://localhost:8000/ws/serp
      - VITE_API_KEY=${LIVE_MODE_TOKEN:-dev-token-123}
    volumes:
      - ../ui/src:/app/src
      - ../ui/public:/app/public
    depends_on:
      - python-api
    command: npm run dev -- --host 0.0.0.0

volumes:
  redis_data: 